account for duplicates
OpenFn/gife pull request #10
Opened 2023-09-05 07:47 UTC by bryceVeraSolutions

assign multiple tags to single contact

2023-09-05 16:08 UTC, mtuchi requested changes
@bryceVeraSolutions the changes you proposed does not work
have you run this workflow locally to confirm that it will give you the desired output?

2023-09-07 07:24 UTC, bryceVeraSolutions commented on jobs/getCampaignMembers.js
> +      //subscriber_hash: member.Email,
Yes this is working

2023-09-07 07:24 UTC, bryceVeraSolutions commented
@mtuchi updated the pull request, ready for review

2023-09-07 09:31 UTC, mtuchi commented on jobs/getCampaignMembers.js
> +      //subscriber_hash: member.Email,
@bryceVeraSolutions please remove this comment and share your feedback with Willian why we don't need this

2023-09-07 09:32 UTC, mtuchi commented on jobs/getCampaignMembers.js
> +    console.log(
@bryceVeraSolutions please remove this `console.log()`. It's not important on PROD

2023-09-07 09:33 UTC, mtuchi commented on jobs/getCampaignMembers.js
> +    console.log(
@bryceVeraSolutions please remove this console.log

2023-09-07 09:35 UTC, mtuchi requested changes
Hiya @bryceVeraSolutions please work on the changes i have requested, Once those are done you can go ahead and merge this PR and share an update on slack for Willian to proceed testing the workflow

2023-09-07 10:53 UTC, bryceVeraSolutions commented on jobs/getCampaignMembers.js
> +      //subscriber_hash: member.Email,
made the updates

2023-09-07 10:53 UTC, bryceVeraSolutions commented on jobs/getCampaignMembers.js
> +    console.log(
removed it

2023-09-07 10:53 UTC, bryceVeraSolutions commented on jobs/getCampaignMembers.js
> +    console.log(
removed it

2023-09-07 10:55 UTC, bryceVeraSolutions commented
@mtuchi I made all the requested updates and am merging to main

2023-09-07 10:56 UTC, merged