1 add or update members and tags
OpenFn/gife pull request #3
Opened 2023-08-23 06:19 UTC by bryceVeraSolutions

2023-08-25 06:56 UTC, mtuchi requested changes
@bryceVeraSolutions thanks for cleaning up the job code, this looks great 
Just a tiny fix on `addOrUpdateMemberTags.js`

I left you a comment can you work on that, and make the workflow is running successful ?

2023-08-25 06:56 UTC, mtuchi commented on jobs/addOrUpdateMemberTags.js
> +  'membersToUpdate[*]',
@bryceVeraSolutions  This does not look accurate because your returning `members` array in `getCampaignMembers` not `membersToUpdate, membersToCreate`

2023-08-25 07:02 UTC, mtuchi commented on workflow.json
@bryceVeraSolutions 
Since we have two workflow, Can you rename this to `worflow-1.json`, So that we it's easier to remember when we merge to main

2023-08-25 07:07 UTC, bryceVeraSolutions commented on workflow.json
@mtuchi this has been done

2023-08-28 06:00 UTC, mtuchi approved these changes
This PR looks good, and ready to be merged

2023-08-28 06:02 UTC, merged